function filtre_interfata(R,L,C,tip)

Fig=figure('Name','Filtre RLC ',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.7 0.8],...
    'Color','#FFEBCD',...
    'NumberTitle','off');  

f=uimenu('Label','Documentatie');
uimenu(f,'Label','Titlu proiect','Callback','open(''Titlu proiect - web page.htm'')');
uimenu(f,'Label','Descriere proiect','Callback','open(''Descriere proiect - web page.htm'')');
uimenu(f,'Label','Ecuatii proiect','Callback','open(''Ecuatii proiect - web page.htm'')');
uimenu(f,'Label','Utilizare interfata','Callback','open(''Prezentare proiect GAC.pptx'')');
uimenu(f,'Label','Bibliografie','Callback','open(''Bibliografie - web page.htm'')');
uimenu(f,'Label','Iesire','Callback','close');

%Rezistenta
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.085,0.88,0.1,0.03],...
          'BackgroundColor','#9932CC',...
          'FontSize',10,...
          'FontWeight','b',...
          'String','Rezistenta R:');

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.09,0.83,0.05,0.03],...
    'FontSize',10,...
    'String',R,...
    'Callback','R=str2num(get(gco,''String''));close;filtre_interfata(R,L,C,tip)');

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.15,0.83,0.05,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',12,...
    'String','[Ohm]');
%Inductanta

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.085,0.78,0.1,0.03],...
    'BackgroundColor','#9932CC',...
    'FontSize',10,...
    'FontWeight','b',...
    'String','Inductanta L:');

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.09,0.73,0.05,0.03],...
    'FontSize',10,...
    'String',L,...
    'Callback','L=str2num(get(gco,''String''));close;filtre_interfata(R,L,C,tip)');

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.15,0.73,0.03,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',10,...
    'String','[H]');

%Capacitatea 

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.085,0.68,0.1,0.03],...
    'BackgroundColor','#9932CC',...
    'FontSize',10,...
    'FontWeight','b',...
    'String','Capacitatea C:');

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.09,0.63,0.05,0.03],...
    'FontSize',10,...
    'String',C,...
    'Callback','C=str2num(get(gco,''String''));close;filtre_interfata(R,L,C,tip)');

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.15,0.63,0.03,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',10,...
    'String','[F]');


uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.84 0.8 0.12 0.19],...
           'value',tip,...
           'String','FTJ|FTS|FTB|FOB',...
           'FontSize',10,...
           'ForegroundColor','b',...
           'Callback','tip=get(gco,''value'');close;filtre_interfata(R,L,C,tip)');
      

%Calcule -> ecuatii
Q=sqrt(L/C)./R;
f0=1/(2*pi*sqrt(L*C));
%-------------------------------------------------------
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.33,0.12,0.03],...
          'FontSize',13,...
          'BackgroundColor','#7B68EE',...
          'String',['Q = ',num2str(Q)]); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.29,0.12,0.03],...
          'FontSize',13,...
          'BackgroundColor','#7B68EE',...
          'String',[' f0 = ',num2str(fix(f0)),' Hz ']); 
      
x=logspace(-1,1,300);
f=x.*f0;
w=2.*pi.*f;
w0=2.*pi.*f0;
subplot('Position',[0.01 0.4 0.28 0.2]);

switch(tip)
     case 1 
          [im, co]=imread('ftjRLC.jpg');
          image(im),colormap(co);
          axis off; 
          Titlul='Filtru Trece Jos';
          
                num=1./(j*w.*C) ;
                den=R+j*w.*L+1./(j*w.*C);
                a=8*Q.^4-4*Q.^2+1;
                b=sqrt((2*Q.^2-1+sqrt(a))/(2*Q.^2));
                fmax=b*f0;
                flim=fmax;
                faza1=(180./pi)*angle(Q./(Q*(1-b.^2)+j*b));
                faza0=-90;
      case 2
          [im, co]=imread('ftsRLC.jpg'); 
          image(im),colormap(co);
          axis off;
          Titlul='Filtru Trece Sus';


            num= j*w.*L ;
            den=R+j*w.*L+1./(j*w.*C);
                a=8*Q.^4-4*Q.^2+1;
                b=sqrt((-2*Q.^2+1+sqrt(a))/(2*Q.^2));
                fmax=b*f0;
                flim=fmax;
                faza1=(180./pi)*angle(-b.^2*Q./(Q*(1-b.^2)+j*b));
                faza0=90;
      case 3
          [im, co]=imread('ftbRLC.jpg');
          image(im),colormap(co);
          axis off; 
          Titlul='Filtru Trece Banda';    

     
              num=R; 
              den=R+j.*w.*L+1./(j.*w.*C);
                fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
                fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
                Bf=fmax-fmin;
                faza1=45;
                faza2=-45;
     case 4          
         [im, co]=imread('fobRLC.jpg'); 
          image(im),colormap(co);
          axis off; 
          Titlul='Filtru Opreste Banda'; 

     
            num= j*w.*L + 1./(j*w.*C);
            den=R+j*w.*L+1./(j*w.*C);
                fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);
                fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
                Bf=fmax-fmin;

                faza1=-45;
                faza2=45;

end

%evaluarea formulei Uies/Uin
     h=abs(num./den);
%calculul fazei semnalului
     phase=angle(num./den)*180./pi;
%calculul castigului
              gain=20*log10(h);
              
                     
           subplot('Position', [0.35 0.72 0.6 0.23]);
           if (tip==1)||(tip==2)
            semilogx(f,h,'y',flim,1./sqrt(2),'b','LineWidth',2);
           else
           semilogx(f,h,'y',fmin,1./sqrt(2),'b',fmax,1/sqrt(2),'b','LineWidth',2);
           end
           grid on;
           xlabel('Frecventa [ Hz ]');
           ylabel('| u2 / u1 | ');
           
           title(Titlul,'Fontweight','b','FontSize',14,'Color','black');
           legend(' |u2 / u1 |');
          
   if (tip==3)||(tip==4)
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.26,0.15,0.03],...
          'FontSize',13,...
          'BackgroundColor','#7B68EE',...
          'String',['fmax = ',num2str(fix(fmax)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.22,0.15,0.03],...
          'FontSize',13,...
          'BackgroundColor','#7B68EE',...
          'String',['fmin = ',num2str(fix(fmin)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.19,0.15,0.03],...
          'FontSize',13,...
          'BackgroundColor','#7B68EE',...
          'String',['Bf = ',num2str(fix(Bf)),' Hz ']); 
           else
           uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.25,0.15,0.03],...
          'FontSize',13,...
           'BackgroundColor','#7B68EE',...
          'String',['flim = ',num2str(fix(fmax)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.22,0.15,0.03],...
          'FontSize',13,...
          'BackgroundColor','#7B68EE',...
          'String',['faza = ',num2str(fix(faza1)),' grade ']); 

           end
           
           subplot('Position', [0.35 0.4 0.6 0.23]);
                              if  (tip==1)||(tip==2)
           semilogx(f,phase,'b',flim,faza1,'k','LineWidth',2);
                                 else
           semilogx(f,phase,'b',fmin,faza1,'r',fmax,faza2,'r','LineWidth',2);
                              end
           grid on;
           xlabel('Frecventa [ Hz ]');
           ylabel('Faza [ grade ]');
           title('Faza semnalului','Fontweight','b');
           legend('Faza');
           
             subplot('Position', [0.35 0.07 0.6 0.23]);
                      if (tip==1)|(tip==2)
           semilogx(f,gain,'r',flim,-3,'ko','LineWidth',2);
                      else
           semilogx(f,gain,'r',fmin,-3,'ko',fmax,-3,'ko',f0,0,'ro','LineWidth',2);
                      end
           grid on;
           xlabel('Frecventa [ Hz ]');
           ylabel('Castigul [ dB ]');
           title('Castigul','fontweight','b');
           legend('Castigul');
           
 uicontrol('Style','pushbutton',... 
 'Units','normalized',...
 'Position',[0.1 0.02 0.08 .05],...
 'string','Inapoi',...
 'Callback','close; rlcserie_interfata(R,L,C)');